baseURL: localhost:8000
languageCode: en-us
title: David Przybilla Archive
copyright: © 2022 X
googleAnalytics:
# paginate specifies the maximum number of posts displayed on the home page.
paginate: 20
# theme specifies the name of the theme to be used.
theme: minima
# defaultContentLanguage specifies the default language to use.
defaultContentLanguage: en
# language.x setup
languages:
  en:
    languageName: EN
    weight: 1

# author specifies your name, a slogon and your brief self-introduction.
author:
  name: David Przybilla
  status: Am currently living on Earth 🌍
  description: |
     something
params:
  # greet specifies greeting words.
  greet: Hello :)
  # subtitle speficies a subtitle displayed right after the site title.
  subtitle:
  # switch specifies two emojis to be used as the button toggling color themes.
  switch: ["🌚", "🌝"]
  # defaultTheme specifies a default theme to be used.
  # currently available options: light, dark, system.
  defaultTheme: system
  # displayDate speficies whether or not to display post date on the home page.
  displayDate: true
  # displayDescription specifies whether or not to display post description on
  # the hoem page.
  displayDescription: true
  # selectable specifies if your post content can be selected.
  selectable: true
  # social is an array containing as many as social accounts to be displayed
  # in the buttom of every page.
  social:
    - name: "twitter"
      url: "https://twitter.com/dav009"
    - name: "email"
      url: "mailto:dav.alejandro@gmail.com"
    - name: "github"
      url: "https://github.com/dav009"
    - name: "rss"
      url: "/index.xml"

  # math plugin
  math:
    enable: false
    provider: katex

  # diagram plugin
  diagram:
    enable: false
    provider: mermaid

  # comment plugin
  comment:
    enable: false

# menu.main is an array containing what is used as the navigator.
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - identifier: about
      name: "About"
      url: "/about/"
      weight: 2
    - identifier: tags
      name: "Tags"
      weight: 3


# taxonomies defines ways to classify yout posts. Below are some presets that
# most bloggers use, so you can replace them with whatever you like.
taxonomies:
  category: categories
  tag: tags
  series: series

# markup.highlight has two keys set to make sure that the syntax highlighting
# in your posts are rendered correctly, so do not edit them.
markup:
  highlight:
    lineNos: true
    noClasses: false

